### ISSUE TITLE
Show devices connected to discovered UPnP enabled device.

### ISSUE THREAD

**Issue by siredwin** [huin/goupnp#29]
I am wondering if this is beyond the scope of this project.
I want to show devices connected to my UPnP router in the subnet.

I have been reading the godocs but I can't seem to figure this out

**Comment by huin** [comment]
Do you mean devices using the router for their connection to the internet?

If so - I haven't looked at the SOAP methods provided by UPnP services for internet gateways, but I don't recall a service that provides such a capability.

I could have missed such a thing, however. I suggest checking the standards docs to see if they talk about such things:

* http://upnp.org/specs/gw/UPnP-gw-InternetGatewayDevice-v1-Device.pdf
* http://upnp.org/specs/gw/UPnP-gw-InternetGatewayDevice-v2-Device.pdf

**Comment by siredwin** [comment]
Ok. This can be solved by looking at device leases file.
