### ISSUE TITLE
Fail on http post request to router.

### ISSUE THREAD

**Issue by hyunsooda** [huin/goupnp#32]
<img width="777" alt="스크린샷 2019-09-15 오전 3 12 05" src="https://user-images.githubusercontent.com/12508269/64912186-9ea8a800-d766-11e9-8760-1ff1d2a04b65.png">

In this image, it shows that device(ipTIME N104R3) is detected but http post request was fail.
I have a long time to find why my router doesn't response on post request. so I have took a specification about my router but there are no statement related to soap... so I have no idea whether my router cannot response or other problem is there...

Definition of my function 
```
func AddPortMapping_ver1(PrivateIP string, ExternalPort uint16, InternalPort uint16, Protocol string) {
	clients, errors, err := internetgateway1.NewWANIPConnection1Clients()

	if errors != nil {
		return
	}
	if err != nil {
		return
	}
	for _, client := range clients {
		if err := client.AddPortMapping(PrivateIP, ExternalPort, Protocol, InternalPort, PrivateIP, true, "test", 0); err != nil {
			fmt.Println(err.Error())
		}
	}
}
```
And call AddPortMapping_ver1() in main function
```
AddPortMapping_ver1("192.168.0.2", 7871, 7871, "TCP") // my computer address is 192.168.0.2 and 192.168.0.1 is address of router
```

Your library says
<img width="686" alt="스크린샷 2019-09-15 오전 3 22 02" src="https://user-images.githubusercontent.com/12508269/64912291-09a6ae80-d768-11e9-9bb1-8b8c6f39331d.png">

Do you have any idea about this problem?

Sorry for my English.

**Comment by huin** [comment]
This is a bit of an odd one. It sounds like the router might be responding with a malformed HTTP header when responding to the POST.

To check, you could use a packet sniffer while running your code to look at network traffic between the computer making the SOAP call to the router and the router itself. Maybe filter for traffic to/from 192.168.0.1. You should be able to find an HTTP request that goes to the router.

I *suspect* from the error that the router is returning a first line response that looks something like:

```
HTTP1.1 200 OK
<some HTTP headers ...>
```

The `200 OK` bit is irrelevant for this specific error. The `HTTP1.1` is what I am focusing on, and it *should* be `HTTP/1.1` (i.e with a slash). If that's the case, then the router's SOAP implementation is buggy. That might be something you can work around, though but first we should confirm if that's the case.

If that's not the case, would you be able to share the HTTP request (and response if there is one) from that single SOAP request?

**Comment by hyunsooda** [comment]
Hello @huin  :)
Thanks for kind replying!

<img width="1413" alt="스크린샷 2019-09-22 오전 7 49 34" src="https://user-images.githubusercontent.com/12508269/65380049-da66e300-dd0d-11e9-83a7-dddc8ef7e312.png">
This is packet picture between 192.168.0.1(my router) and 192.168.0.2(my desktop)
In this picture, I could see HTTP get method to get InternetGatewayDevice.xml, response on get method(http://192.168.0.1:1780/InternetGatewayDevice.xml) and post method(controlWANIPConnection HTTP1.1)

Picture 2 (Get response about InternetGatewayDevice)
<img width="823" alt="스크린샷 2019-09-22 오전 7 49 41" src="https://user-images.githubusercontent.com/12508269/65380078-71339f80-dd0e-11e9-9c42-64fac5821b0a.png">

Picture 3 (HTTP Post)
<img width="1044" alt="스크린샷 2019-09-22 오전 7 49 45" src="https://user-images.githubusercontent.com/12508269/65380082-890b2380-dd0e-11e9-94d8-0cf60668edbb.png">

Picture 4 (Bad request ...??)
<img width="1005" alt="스크린샷 2019-09-22 오전 7 49 51" src="https://user-images.githubusercontent.com/12508269/65380084-90cac800-dd0e-11e9-8211-705116fbd69f.png">

Can you give an advice based on these information?
I will call my router company to figure out that whether my router model is supported SOAP response or not tomorrow(today is holiday in Korean time)

**Comment by huin** [comment]
Interesting. So it confirms my suspicion that the router is returning a badly formed HTTP response. That might be something that could be worked around by injecting a transport into the SOAP client's `HTTPClient`, but it sounds like it wouldn't be worth doing so because we're getting a 400 bad request anyway. I'm guessing that it's their error response handler that's producing the bad HTTP header, presumably they only tested the success paths.

In terms of getting something working for you, this is tricky: it would be necessary to work out what the router doesn't like about the SOAP request sent by the library. Unfortunately all we've got to go on is "Bad Request". This could mean something that the router didn't like about the HTTP headers or the XML body, it's not clear. Working this out would presumably be trial and error with manually constructed SOAP requests. If that was worked out, then there's the question of how the goupnp library might be adapted to being able to send them. Unfortunately, without knowing exactly what the router is unhappy about there's not much more I can add here :(

**Comment by hyunsooda** [comment]
Okay... I have last 2 questions :

1. you mean that this problem is relevant with my router implementation?

2. I have no experience what your library works because your library functions don't work in my environment. so my question is your 'AddPortMapping' function perform that my router force to open the port given? If so, is this not illegal? is this standard? I know that Ethereum, Bitcoin, Bittorrent have tech like this.

**Comment by huin** [comment]
1. Answer: half yes, half unknown.

* The half yes bit is just about the malformed "HTTP1.1 400 Bad Request" bit, which is malformed, and the Go HTTP library is rejecting it.
* The half unknown bit leads onto the next answer.

2. Answer: I don't know that there's anything wrong with the library, as far as I know, others have managed to use it (or other SOAP functions) for their routers. It's possible that your router doesn't support it - you could check the response XML from http://192.168.0.1:1780/InternetGatewayDevice.xml to see if it's one of the supported methods. Check if that XML contains "AddPortMapping". If not, then it's probably not supported (the goupnp library doesn't actually check the XML). If it is present, then I suspect that it's a problem with how the router parses the HTTP request or the SOAP envelope inside it.

**Comment by hyunsooda** [comment]
Oh! absolutely there is no 'AddPortMapping' in http://192.168.0.1:1780/InternetGatewayDevice.xml

It means that my router no support AddPortMaping which is standard in UPnP?

I was wondering that AddPortMapping function in your library performs that my router force to open given port? (please answer about this.. I really want to know..! )

**Comment by huin** [comment]
Ah, that explains it then. I'm not 100% sure, but I think that routers don't have to implement all the features provided. The goupnp library assumes that all the features are provided.

Unfortunately if the router doesn't offer that SOAP method, then the goupnp library won't be able to forward the port.

**Comment by hyunsooda** [comment]
OK, alright. 

The last question which was given to you is not related to your library. 

I know that "AddPortMaping" is a standard function that force router to open given port.
Is your library also implemented this feature?

**Comment by huin** [comment]
The goupnp library does implement it, yes.

**Comment by hyunsooda** [comment]
Thanks.. 

This is really last question... 

Do you know why this feature is standard? 
Some people may dislike that their port is automatically opened by third-party application.
I searched about this but there is no reason anywhere.

**Comment by hyunsooda** [comment]
Oh! Jesus! I have found the solution :)

The solution is 'miniupnp'

<img width="878" alt="스크린샷 2019-09-22 오후 11 42 08" src="https://user-images.githubusercontent.com/12508269/65389580-b5688380-dd92-11e9-962b-9e7ea3c625c9.png">

<img width="372" alt="스크린샷 2019-09-22 오후 11 37 44" src="https://user-images.githubusercontent.com/12508269/65389584-bc8f9180-dd92-11e9-8538-eea75231d264.png">

Very cool :)

Thanks for very kind replying @huin :)

**Comment by huin** [comment]
I hope it helped :)

**Comment by etimes2008** [comment]
func NewSOAPClient(endpointURL url.URL) *SOAPClient {
	timeout := time.Duration(3 * time.Second)
	tr := &http.Transport{
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
	}
	return &SOAPClient{
		EndpointURL: endpointURL,
		HTTPClient: http.Client{
			Timeout:   timeout,
			Transport: tr,
		},
	}
}
this is ok！
