### ISSUE TITLE
goupnp.go:109: undefined: charset.NewReaderByNam

### ISSUE THREAD

**Issue by inasacu** [huin/goupnp#7]
when running the following:
go get -u github.com/huin/goupnp
I am getting an error on mac yosemite latest version

# github.com/huin/goupnp
/usr/local/bin/src/github.com/huin/goupnp/goupnp.go:109: undefined: charset.NewReaderByNam

**Comment by huin** [comment]
Dang. https://github.com/golang/net/commit/6460565bec1e8891e29ff478184c71b9e443ac36 looks like it broke this.

**Comment by huin** [comment]
Thanks for reporting, let me know if that doesn't work.
